### ISSUE TITLE
Fake players in the log?

### ISSUE THREAD

**Issue by Xtremethegamerz** [Lululuz/FutBud#10]
I went to sleep on the night, and I left it with 3 players to try and buy: Marcos Rojo, Jackson Martinez and Pedro. It said he bought 3 Pedro and 3 Jackson Martinez, and sold just 1 Pedro. When I opened the webapp, in the morning, there were 4 Pedro instead of 3, and none did sell. Also, there were no Jackson Martinez. Am I doing something wrong? Does it look for all the players in the list by default or I should check something?

**Comment by Lululuz** [comment]
Tradepile seems to be bugged see
https://github.com/Lululuz/FutBud/issues/6
https://github.com/Lululuz/FutBud/issues/5
Dunno whats the reason for now

**Comment by Xtremethegamerz** [comment]
If I'm not wrong,they're both on PS4, while I am on Xbox One. Also, mine never gives back Tradepile error, it just says it bought players he never bought really.

**Comment by Lululuz** [comment]
https://github.com/Lululuz/FutBud/issues/6
