### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by Lululuz** [Lululuz/FutBud#12]
Hey everyone,

as already mentioned my PS4 account is transfermarket locked (needs 15 games to be unlocked). I can therefore do no debug/implement improvements to transfermarket related features.

If someone with a PS4 (I don't own one) is willing to unlock my account this would be really!! helpfull. If you own any other console you can also simply create an account for free!

Thank you!
Greetings

**Comment by M-Denz** [comment]
Hello Lululuz, I don't mind playing the games for you :). Send me the details in a private message and I'll play the games for you and I promise from the bottom of my heart I will not do anything else besides that. And to prove it just change your password afterwards.

Let me know when you can if that is possible. Thank you
M-Denz

**Comment by Lululuz** [comment]
There are no private messages on github :) just write me an email (support@futbud.com) so you don't have to post yours in public. You can send me a skype addy if you prefer that.

No worrys about the account, there is nothing on it anyway :D

**Comment by M-Denz** [comment]
Sure, Here's my skype in in this file - the links is only up for ten minutes since this message was posted.
http://txt.do/5uqyw

Thanks
M-Denz

**Comment by Lululuz** [comment]
missed it :/ just write a mail

**Comment by M-Denz** [comment]
Ok, done! :)  I'll wait for the details.

**Comment by M-Denz** [comment]
Ok Lululuz, finally done! I sent you a message, read it when you can :).

**Comment by Lululuz** [comment]
Yep, already saw it, thank you :)
