### ISSUE TITLE
Suggestions + Question

### ISSUE THREAD

**Issue by Xtremethegamerz** [Lululuz/FutBud#14]
I have a few suggestion that I found using the program:

1) You should add in the log for how much a player has been bought, instead of just showing when he gets bought
2) You should add the feature to look for non-players too. For example, looking for Bundesliga managers for 200 is a good way to make money, or finding position modifiers for cheap.
3) You should make the user decide whether to sell or not the players it buys. For example, I used an old version of an autobuyer of mine to snipe players for my own team, and then keep them (like this, I bought a Thiago Silva for 7k below his BIN)

Also my question is: With this kind of autobuyer, can you get an account ban from EA? (Not the transfer market ban)

**Comment by Lululuz** [comment]
There is a topic for suggestions, please use that :)
1) It should show the buyprice (altough it is the one in your list, I will change that
2) As said several times I have no access to the transfermarket --> help needed see https://github.com/Lululuz/FutBud/issues/12
3) If you set the sellprice to 0 the player should not be sold. It's not tested tought.

Reparding your question: I think the only ban you can get is a ban from Ultimate Team, no account ban or whatever

**Comment by Xtremethegamerz** [comment]
This means, If I use this I could get myself banned from UT like you would for buying coins?

**Comment by Lululuz** [comment]
As I said
