### ISSUE TITLE
How do I use it? (Autoprice)

### ISSUE THREAD

**Issue by OthonGBR** [Lululuz/FutBud#15]
How do I use it?
![como funcion](https://cloud.githubusercontent.com/assets/14895784/11768698/ab485874-a1bb-11e5-9446-f68b7d211c60.png)

**Comment by Lululuz** [comment]
It's part of the autoprice feature which updates your prices automaticly every 5 minutes. It takes the lowest price from the market and sets the prices according to your percentage settings.
Example: 
Lowest price that is found is 100k so the buyprice will be 85k and the sellprice 98k with your posted settings.
