### ISSUE TITLE
Selling

### ISSUE THREAD

**Issue by cawk** [Lululuz/FutBud#16]
this is perfect however it doesnt list the player after purchasing please could you fix this

**Comment by Lululuz** [comment]
For me it's working fine. Check the latest version (0.9.5.1) which commited today. :)

**Comment by cawk** [comment]
ah thank you working fine with latest update ive also added myself a timer for the auto prices so if you leave it for long time it will constantly update maybe add that for everyone

**Comment by Lululuz** [comment]
Well actually there is a timer. If the bot runs it checks prices every 5 minutes.

**Comment by cawk** [comment]
oh okay i added a custom one in there anyway as i didnt see your timer in there
also special cards are not found?

**Comment by Lululuz** [comment]
https://github.com/Lululuz/FutBud/issues/1

**Comment by cawk** [comment]
when i search player this is all i find ronaldo has many informs and special cards however only finds his normal card https://gyazo.com/ae2d4b45ab579d9f8433c8d8cacb9968

**Comment by Lululuz** [comment]
This is by purpose since it wouldnt make sense if you would put them to your list but the search is not working for them. Remove line 104 of the FormAddPlayer

```c#
//skip informs
if(item.color.Contains("totw")|| item.color.Contains("motm") || item.color.Contains("purple") || item.color.Contains("legend"))
   continue;
```
if you want to see them but this won't really help you.
