### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by OthonGBR** [Lululuz/FutBud#17]
Suggestion
Be able to snipar players. It would be great! Mainly to former generation that is very difficult to make trading

**Comment by Lululuz** [comment]
There is a suggestion thread please use it. I am sorry but I have no idea what you are trying to say.

**Comment by OthonGBR** [comment]
Sorry that I do not speak English and I communicate by Google Translate.
Have a function of "sniping" players.

**Comment by Lululuz** [comment]
Well that's what it actually does. It searches for player that are beeing sold under the price you set and buys them if possible.
