### ISSUE TITLE
Wrong _profit counting

### ISSUE THREAD

**Issue by yyyyyy01** [Lululuz/FutBud#19]
Hello. It seems that profit is not counted good (it works good with precompiled binaries but for some reason it doesnt work when I recompile it) I used VS 2013 to compile

-5500 + 2500 = 2275

wtf :D

edit: a vidya: https://vid.me/412Q

**Comment by Lululuz** [comment]
Compiling works fine for me. VS 2015. 
Profit calc works like that: I gets and saves the initial credits once you start the application. Then it takes the creditsresponse and substracts the startcredits. The difference is your loss/profit per session.
This calculated profit should always be correct.

_profit = (int)creditsResponse.Credits - _startcredits;

**Comment by yyyyyy01** [comment]
Forgot about EA Tax. I'm stupid. Merry xmas!
