### ISSUE TITLE
Cookie issue

### ISSUE THREAD

**Issue by D4NNY1000000** [Lululuz/FutBud#2]
Saved my login details, logged in, closed the app.
Opened the app again and changed my email address by one character to a different account I setup but still logged me in as the previous user.

**Comment by Lululuz** [comment]
Sure, the cookie saves your session and sets it if the cookie.dat is found for the next login. Save login + cookie stuff is only supposed to work with one user at the moment. Delete the cookie.dat if you change user or completly dont use the save login function.

**Comment by D4NNY1000000** [comment]
Ok cool, just thought I'd let you know

**Comment by Lululuz** [comment]
I changed the account management and cookie handling. Should be fixed now when switching accounts.

**Comment by D4NNY1000000** [comment]
Good job, seems to be working great now.
