### ISSUE TITLE
Is the version of UltimateTeam.Toolkit you use modified?

### ISSUE THREAD

**Issue by omrihaviv** [Lululuz/FutBud#3]
I wanted to add changes to the library UltimateTeam.Toolkit that I made myself to your project but it keeps crashing. Is it modified version which means I can't use the main branch of UltimateTeam.Toolkit?

Thanks.

**Comment by Lululuz** [comment]
Yep, I made the Cookiecontainer public with a getter and setter. I'll fork the toolkit and do my changes in there so you can see what I modified. Fell free to add your stuff there then :)

**Comment by omrihaviv** [comment]
Great. Thanks!
