### ISSUE TITLE
Not Enough Credits Cycle Error - FUTBUD

### ISSUE THREAD

**Issue by M-Denz** [Lululuz/FutBud#7]
Platform - Windows
Platform Version - Windows 7 Professional
Architecture - x64

FUTBUD Platform - PS4

Hello, OK coincidentally if there is an auction found AND it is the first player on the list AND you don't have enough credits, then instead of jumping to the next player in the list, it will just repeatedly search the first item in the list again and again without looking at the others. If all the 3 things happened on anything besides the first item OR there are no auctions but you don't have enough credits, then it will successfully cycle through the whole list without always beings stuck on the first one.

I'll upload a picture in a bit.

Thank you :)

M_Denz

**Comment by Lululuz** [comment]
Should be fixed with the new commit, please check.
