### ISSUE TITLE
Credit Update Bug - FUTBUD

### ISSUE THREAD

**Issue by M-Denz** [Lululuz/FutBud#8]
Platform - Windows
Platform Version - Windows 7 Professional
Architecture - x64

FUTBUD Platform - PS3(PS4 I believe so as well but I can not tell since the trade pile error it cannot sell, only buy.)

Hello, Normally when player has been brought and sold, the credits do not update - it is only when you turn off and on the buying process that it updates and shows your new credits.

I'll try and upload a picture in a bit.

Thank you :)
M_Denz

**Comment by Lululuz** [comment]
The credits get checked with the tradepile request and if you buy a player. Please check the new commit, I moved the tradepile check into the finally clause.
